name: Deploy to GitHub Pages

on:
    push:
        branches: ["master"]
    workflow_dispatch:
permissions:
    contents: read
    pages: write
    id-token: write
concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Pages
              uses: actions/configure-pages@v3
            - name: Create bundle.js
              run: |
                  npm install
                  npm run build
            - name: Delete Unnecessary Files
              run: |
                  rm -rf .git
                  rm -rf .github
                  rm -rf .gitignore
                  rm -rf .vscode
                  rm -rf node_modules
                  rm -rf package-lock.json
                  rm -rf package.json
                  rm -rf README.md
                  rm -rf LICENSE
                  rm -rf mdesign.js
            - name: Create robots.txt
              run: |
                  echo "User-agent: *" >> robots.txt
                  echo "Disallow: /" >> robots.txt
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  artifact-name: prod
                  path: .

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
